name: tests
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # setting just 3.10 bugs out for some reason
        python-version: [3.7, 3.8, 3.9, 3.10.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: install and configure poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.2
      - run: |
          poetry config virtualenvs.create false
          poetry install
      - run: |
          pre-commit install
          pre-commit run --all-files
